version: '3.4'

## PLEASE provide values for relevant environment variables (e.g, GIT_USER) in an accompanying .env file
## the .env file will not be checked in to version control

services:
  ci:
    # image: appertaopeneyes/ci
    build:
      context: ./
    environment:
      SELENIUM_BASE_URL: "http://ci"
      SELENIUM_WD_HOST: http://selenium:4444/wd/hub
      TESTS_TO_RUN: "PHPUNIT;BLAHH;BEHAT"
      # TESTS_TO_RUN: ""
      NO_RESET_DB_BETWEEN_TESTS: "true"
      BUILD_BRANCH: docker/behat
      PHPUNIT_CLI_SWITCHES: "/var/www/openeyes/protected/tests/unit/controllers/BaseControllerTest.php"
    secrets:
      - source: SSH_PRIVATE_KEY
    ports:
      - "8080:80"
      - "2222:22"
    stdin_open: true
    tty: true
    depends_on:
      - selenium
    volumes:
      - ../web/init.sh:/init.sh

  selenium:
    image: selenium/standalone-chrome-debug:3.14
    container_name: selenium
    ports:
      - "4444:4444"
      - "5900:5900"
      - "9515:9515"
    environment:
      VNC_NO_PASSWOR: "1"
      SCREEN_WIDTH: "1920"
      SCREEN_HEIGHT: "1080"
    volumes:
      - /dev/shm:/dev/shm

secrets:
  SSH_PRIVATE_KEY:
    file: ~/.ssh/id_rsa
